# Generated by Django 5.1.4 on 2025-01-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('product', models.CharField(choices=[('Product 1', 'Product 1'), ('Product 2', 'Product 2'), ('Product 3', 'Product 3')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('order_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
